In [79]:
import pandas as pd
import numpy as np
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

from sklearn.linear_model import Lasso

In [46]:
df=pd.read_csv('dataset/final.csv')
df.head()

Survived  Pclass   Age  SibSp  Parch     Fare  male  Q  S
0         0       3  22.0      1      0   7.2500     1  0  1
1         1       1  38.0      1      0  71.2833     0  0  0
2         1       3  26.0      0      0   7.9250     0  0  1
3         1       1  35.0      1      0  53.1000     0  0  1
4         0       3  35.0      0      0   8.0500     1  0  1

# 1. Dividing the dataset

In [47]:
X = df.drop('Survived', axis=1)
X.head()

Pclass   Age  SibSp  Parch     Fare  male  Q  S
0       3  22.0      1      0   7.2500     1  0  1
1       1  38.0      1      0  71.2833     0  0  0
2       3  26.0      0      0   7.9250     0  0  1
3       1  35.0      1      0  53.1000     0  0  1
4       3  35.0      0      0   8.0500     1  0  1

In [48]:
y = df['Survived']
y.head()

0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64

In [49]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2)

In [50]:
y_train.shape

(712,)

In [51]:
X_train.shape

(712, 8)

# Logistic Regression

In [57]:


lr = LogisticRegression()
lr.fit(X_train, y_train)

pred = lr.predict(X_test)
accuracy = confusion_matrix(y_test,pred)
accuracy = round(accuracy_score(y_test, pred),2)
print('Model Accuracy: ', accuracy*100)
confusion_matrix(y_test, pred)

Model Accuracy:  80.0


C:\Users\Aman\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


array([[91, 15],
       [21, 52]], dtype=int64)

# Random Forest Classifier

In [74]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(criterion='entropy', max_depth=3)
rf.fit(X_train, y_train)
pred = rf.predict(X_test)
accuracy = round(accuracy_score(y_test, pred),2)
print('Model Accuracy :', accuracy*100)
confusion_matrix(y_test, pred)

C:\Users\Aman\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


Model Accuracy : 83.0


array([[96, 10],
       [21, 52]], dtype=int64)

# Decision Tree Classifier

In [114]:
from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier(criterion='entropy', max_depth=3)
dt.fit(X_train, y_train)
pred = dt.predict(X_test)
accuracy = round(accuracy_score(y_test, pred),2)
print('Model Accuracy :', accuracy*100)

confusion_matrix(y_test, pred)

Model Accuracy : 80.0


array([[92, 14],
       [21, 52]], dtype=int64)